title: Tommy Blog
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: 
  github: https://github.com/ainochi-kor

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ainochi-kor.github.io/"